import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { fileURLToPath } from "url";

// jszip 依赖链里的旧浏览器垫片会 document.createElement("script")，被上架审查当“运行时创建 script 元素”。
// 两者在 Obsidian 里都走不到（见 shims/*.cjs 注释），直接替换。
const shimLegacySchedulers = {
	name: "shim-legacy-schedulers",
	setup(build) {
		build.onResolve({ filter: /^lie$/ }, () => ({
			path: fileURLToPath(new URL("./shims/lie.cjs", import.meta.url)),
		}));
		build.onResolve({ filter: /^(immediate|setimmediate)$/ }, () => ({
			path: fileURLToPath(new URL("./shims/immediate.cjs", import.meta.url)),
		}));
		// jszip 的 browser 字段会指向 dist/jszip.min.js，里面内联了 lie/immediate 的 IE script 兜底；
		// 改成走 lib/ 源码，再用上面的垫片替掉那两个依赖（见 shims/*.cjs 注释）。
		build.onResolve({ filter: /^jszip$/ }, () => ({
			path: fileURLToPath(new URL("./node_modules/jszip/lib/index.js", import.meta.url)),
		}));
		build.onResolve({ filter: /^readable-stream$/ }, () => ({
			path: fileURLToPath(new URL("./shims/readable-stream.cjs", import.meta.url)),
		}));
	},
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	plugins: [shimLegacySchedulers],
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
